// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module countone_countone_Pipeline_VITIS_LOOP_65_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rand_in_TDATA,
        rand_in_TVALID,
        rand_in_TREADY,
        freq4_V_address0,
        freq4_V_ce0,
        freq4_V_we0,
        freq4_V_d0,
        freq4_V_q0,
        freq5_V_address0,
        freq5_V_ce0,
        freq5_V_we0,
        freq5_V_d0,
        freq5_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] rand_in_TDATA;
input   rand_in_TVALID;
output   rand_in_TREADY;
output  [9:0] freq4_V_address0;
output   freq4_V_ce0;
output   freq4_V_we0;
output  [12:0] freq4_V_d0;
input  [12:0] freq4_V_q0;
output  [11:0] freq5_V_address0;
output   freq5_V_ce0;
output   freq5_V_we0;
output  [12:0] freq5_V_d0;
input  [12:0] freq5_V_q0;

reg ap_idle;
reg rand_in_TREADY;
reg[9:0] freq4_V_address0;
reg freq4_V_ce0;
reg freq4_V_we0;
reg[11:0] freq5_V_address0;
reg freq5_V_ce0;
reg freq5_V_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state6_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln1057_reg_395;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] char2letter_V_address0;
reg    char2letter_V_ce0;
wire   [2:0] char2letter_V_q0;
reg    rand_in_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire   [0:0] icmp_ln1057_fu_142_p2;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [11:0] index4_V_load_reg_399;
wire   [0:0] icmp_ln1061_fu_157_p2;
reg   [0:0] icmp_ln1061_reg_405;
reg   [0:0] icmp_ln1061_reg_405_pp0_iter1_reg;
reg   [9:0] freq4_V_addr_reg_409;
reg    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state5_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
wire   [12:0] select_ln76_fu_192_p3;
reg   [12:0] select_ln76_reg_419;
wire   [11:0] index5_V_fu_235_p2;
reg   [11:0] index5_V_reg_424;
wire    ap_block_pp0_stage2_11001;
reg   [11:0] freq5_V_addr_reg_429;
wire   [12:0] select_ln78_fu_355_p3;
reg   [12:0] select_ln78_reg_434;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln573_1_fu_163_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln68_fu_173_p1;
wire   [63:0] zext_ln573_2_fu_337_p1;
reg   [17:0] i_V_2_fu_64;
wire    ap_loop_init;
reg   [17:0] ap_sig_allocacmp_i_V;
wire   [17:0] i_V_3_fu_148_p2;
reg   [11:0] index4_V_fu_68;
wire   [11:0] index_buf_fu_241_p2;
reg   [11:0] phi_ln1525_2_fu_72;
wire   [11:0] phitmp_fu_279_p2;
wire    ap_block_pp0_stage2;
reg   [7:0] phi_ln1525_1_fu_76;
wire   [7:0] phitmp15_fu_293_p2;
reg   [5:0] phi_ln1525_fu_80;
wire   [5:0] phitmp16_fu_311_p2;
wire   [0:0] tmp_fu_178_p3;
wire   [12:0] add_ln223_fu_186_p2;
wire   [11:0] zext_ln1525_fu_218_p1;
wire   [11:0] add_ln223_5_fu_230_p2;
wire   [11:0] shl_ln1525_fu_213_p2;
wire   [8:0] zext_ln1057_fu_209_p1;
wire   [8:0] zext_ln223_1_fu_226_p1;
wire   [8:0] index_buf_1_fu_247_p2;
wire   [5:0] zext_ln223_fu_222_p1;
wire   [5:0] index_buf_2_fu_257_p2;
wire   [10:0] p_shl3_fu_267_p3;
wire   [11:0] p_shl3_cast_fu_275_p1;
wire   [11:0] zext_ln48_fu_253_p1;
wire   [7:0] p_shl2_fu_285_p3;
wire   [7:0] zext_ln48_1_fu_263_p1;
wire   [4:0] p_shl1_fu_299_p3;
wire   [5:0] p_shl1_cast_fu_307_p1;
wire   [0:0] tmp_4_fu_341_p3;
wire   [12:0] add_ln223_1_fu_349_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

countone_countone_Pipeline_VITIS_LOOP_65_2_char2letter_V #(
    .DataWidth( 3 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
char2letter_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(char2letter_V_address0),
    .ce0(char2letter_V_ce0),
    .q0(char2letter_V_q0)
);

countone_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1057_fu_142_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_V_2_fu_64 <= i_V_3_fu_148_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_V_2_fu_64 <= 18'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        phi_ln1525_fu_80 <= 6'd0;
    end else if (((icmp_ln1057_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        phi_ln1525_fu_80 <= phitmp16_fu_311_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_fu_142_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1061_fu_157_p2 == 1'd1))) begin
        freq4_V_addr_reg_409 <= zext_ln573_1_fu_163_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1061_reg_405 == 1'd1))) begin
        freq5_V_addr_reg_429 <= zext_ln573_2_fu_337_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1057_reg_395 <= icmp_ln1057_fu_142_p2;
        icmp_ln1061_reg_405_pp0_iter1_reg <= icmp_ln1061_reg_405;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_fu_142_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1061_reg_405 <= icmp_ln1061_fu_157_p2;
        index4_V_load_reg_399 <= index4_V_fu_68;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        index4_V_fu_68 <= index_buf_fu_241_p2;
        phi_ln1525_1_fu_76 <= phitmp15_fu_293_p2;
        phi_ln1525_2_fu_72 <= phitmp_fu_279_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        index5_V_reg_424 <= index5_V_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1061_reg_405 == 1'd1))) begin
        select_ln76_reg_419 <= select_ln76_fu_192_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1061_reg_405_pp0_iter1_reg == 1'd1))) begin
        select_ln78_reg_434 <= select_ln78_fu_355_p3;
    end
end

always @ (*) begin
    if (((icmp_ln1057_reg_395 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_V = 18'd0;
    end else begin
        ap_sig_allocacmp_i_V = i_V_2_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        char2letter_V_ce0 = 1'b1;
    end else begin
        char2letter_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            freq4_V_address0 = freq4_V_addr_reg_409;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            freq4_V_address0 = zext_ln573_1_fu_163_p1;
        end else begin
            freq4_V_address0 = 'bx;
        end
    end else begin
        freq4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        freq4_V_ce0 = 1'b1;
    end else begin
        freq4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1057_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln1061_reg_405 == 1'd1))) begin
        freq4_V_we0 = 1'b1;
    end else begin
        freq4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            freq5_V_address0 = freq5_V_addr_reg_429;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            freq5_V_address0 = zext_ln573_2_fu_337_p1;
        end else begin
            freq5_V_address0 = 'bx;
        end
    end else begin
        freq5_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        freq5_V_ce0 = 1'b1;
    end else begin
        freq5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln1061_reg_405_pp0_iter1_reg == 1'd1))) begin
        freq5_V_we0 = 1'b1;
    end else begin
        freq5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1057_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        rand_in_TDATA_blk_n = rand_in_TVALID;
    end else begin
        rand_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1057_reg_395 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        rand_in_TREADY = 1'b1;
    end else begin
        rand_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln223_1_fu_349_p2 = (freq5_V_q0 + 13'd1);

assign add_ln223_5_fu_230_p2 = (zext_ln1525_fu_218_p1 + index4_V_load_reg_399);

assign add_ln223_fu_186_p2 = (freq4_V_q0 + 13'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((rand_in_TVALID == 1'b0) & (icmp_ln1057_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((rand_in_TVALID == 1'b0) & (icmp_ln1057_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((rand_in_TVALID == 1'b0) & (icmp_ln1057_reg_395 == 1'd0));
end

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign char2letter_V_address0 = zext_ln68_fu_173_p1;

assign freq4_V_d0 = select_ln76_reg_419;

assign freq5_V_d0 = select_ln78_reg_434;

assign i_V_3_fu_148_p2 = (ap_sig_allocacmp_i_V + 18'd1);

assign icmp_ln1057_fu_142_p2 = ((ap_sig_allocacmp_i_V == 18'd256004) ? 1'b1 : 1'b0);

assign icmp_ln1061_fu_157_p2 = ((ap_sig_allocacmp_i_V > 18'd4) ? 1'b1 : 1'b0);

assign index5_V_fu_235_p2 = (add_ln223_5_fu_230_p2 + shl_ln1525_fu_213_p2);

assign index_buf_1_fu_247_p2 = (zext_ln1057_fu_209_p1 + zext_ln223_1_fu_226_p1);

assign index_buf_2_fu_257_p2 = (phi_ln1525_fu_80 + zext_ln223_fu_222_p1);

assign index_buf_fu_241_p2 = (phi_ln1525_2_fu_72 + zext_ln1525_fu_218_p1);

assign p_shl1_cast_fu_307_p1 = p_shl1_fu_299_p3;

assign p_shl1_fu_299_p3 = {{char2letter_V_q0}, {2'd0}};

assign p_shl2_fu_285_p3 = {{index_buf_2_fu_257_p2}, {2'd0}};

assign p_shl3_cast_fu_275_p1 = p_shl3_fu_267_p3;

assign p_shl3_fu_267_p3 = {{index_buf_1_fu_247_p2}, {2'd0}};

assign phitmp15_fu_293_p2 = (p_shl2_fu_285_p3 + zext_ln48_1_fu_263_p1);

assign phitmp16_fu_311_p2 = (p_shl1_cast_fu_307_p1 + zext_ln223_fu_222_p1);

assign phitmp_fu_279_p2 = (p_shl3_cast_fu_275_p1 + zext_ln48_fu_253_p1);

assign select_ln76_fu_192_p3 = ((tmp_fu_178_p3[0:0] == 1'b1) ? 13'd4096 : add_ln223_fu_186_p2);

assign select_ln78_fu_355_p3 = ((tmp_4_fu_341_p3[0:0] == 1'b1) ? 13'd4096 : add_ln223_1_fu_349_p2);

assign shl_ln1525_fu_213_p2 = index4_V_load_reg_399 << 12'd2;

assign tmp_4_fu_341_p3 = freq5_V_q0[32'd12];

assign tmp_fu_178_p3 = freq4_V_q0[32'd12];

assign zext_ln1057_fu_209_p1 = phi_ln1525_1_fu_76;

assign zext_ln1525_fu_218_p1 = char2letter_V_q0;

assign zext_ln223_1_fu_226_p1 = char2letter_V_q0;

assign zext_ln223_fu_222_p1 = char2letter_V_q0;

assign zext_ln48_1_fu_263_p1 = index_buf_2_fu_257_p2;

assign zext_ln48_fu_253_p1 = index_buf_1_fu_247_p2;

assign zext_ln573_1_fu_163_p1 = index4_V_fu_68;

assign zext_ln573_2_fu_337_p1 = index5_V_reg_424;

assign zext_ln68_fu_173_p1 = rand_in_TDATA;

endmodule //countone_countone_Pipeline_VITIS_LOOP_65_2
