// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="countone_countone,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.185000,HLS_SYN_LAT=774909,HLS_SYN_TPT=none,HLS_SYN_MEM=7,HLS_SYN_DSP=0,HLS_SYN_FF=863,HLS_SYN_LUT=1531,HLS_VERSION=2021_1}" *)

module countone (
// synthesis translate_off
    kernel_block,
// synthesis translate_on
        ap_clk,
        ap_rst_n,
        rand_in_TDATA,
        rand_in_TVALID,
        rand_in_TREADY,
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

// synthesis translate_off
output kernel_block;
// synthesis translate_on
input   ap_clk;
input   ap_rst_n;
input  [7:0] rand_in_TDATA;
input   rand_in_TVALID;
output   rand_in_TREADY;
input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] ap_return;
reg   [9:0] freq4_V_address0;
reg    freq4_V_ce0;
reg    freq4_V_we0;
reg   [12:0] freq4_V_d0;
wire   [12:0] freq4_V_q0;
reg   [11:0] freq5_V_address0;
reg    freq5_V_ce0;
reg    freq5_V_we0;
reg   [12:0] freq5_V_d0;
wire   [12:0] freq5_V_q0;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_done;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_idle;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_ready;
wire   [11:0] grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_address0;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_ce0;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_we0;
wire   [12:0] grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_d0;
wire   [9:0] grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_address0;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_ce0;
wire    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_we0;
wire   [12:0] grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_d0;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_done;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_idle;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_ready;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_rand_in_TREADY;
wire   [9:0] grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_address0;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_ce0;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_we0;
wire   [12:0] grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_d0;
wire   [11:0] grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_address0;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_ce0;
wire    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_we0;
wire   [12:0] grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_d0;
wire    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start;
wire    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_done;
wire    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_idle;
wire    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_ready;
wire   [11:0] grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq5_V_address0;
wire    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq5_V_ce0;
wire   [9:0] grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq4_V_address0;
wire    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq4_V_ce0;
wire   [37:0] grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_chsq_V_2_out;
wire    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_chsq_V_2_out_ap_vld;
reg    grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start_reg;
reg   [6:0] ap_NS_fsm;
wire    ap_NS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [0:0] tmp_fu_96_p3;
wire   [31:0] ret_fu_104_p4;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    regslice_both_rand_in_U_apdone_blk;
wire   [7:0] rand_in_TDATA_int_regslice;
wire    rand_in_TVALID_int_regslice;
reg    rand_in_TREADY_int_regslice;
wire    regslice_both_rand_in_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start_reg = 1'b0;
#0 grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start_reg = 1'b0;
#0 grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start_reg = 1'b0;
end

countone_freq4_V #(
    .DataWidth( 13 ),
    .AddressRange( 625 ),
    .AddressWidth( 10 ))
freq4_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(freq4_V_address0),
    .ce0(freq4_V_ce0),
    .we0(freq4_V_we0),
    .d0(freq4_V_d0),
    .q0(freq4_V_q0)
);

countone_freq5_V #(
    .DataWidth( 13 ),
    .AddressRange( 3125 ),
    .AddressWidth( 12 ))
freq5_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(freq5_V_address0),
    .ce0(freq5_V_ce0),
    .we0(freq5_V_we0),
    .d0(freq5_V_d0),
    .q0(freq5_V_q0)
);

countone_countone_Pipeline_VITIS_LOOP_59_1 grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start),
    .ap_done(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_done),
    .ap_idle(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_idle),
    .ap_ready(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_ready),
    .freq5_V_address0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_address0),
    .freq5_V_ce0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_ce0),
    .freq5_V_we0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_we0),
    .freq5_V_d0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_d0),
    .freq4_V_address0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_address0),
    .freq4_V_ce0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_ce0),
    .freq4_V_we0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_we0),
    .freq4_V_d0(grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_d0)
);

countone_countone_Pipeline_VITIS_LOOP_65_2 grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start),
    .ap_done(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_done),
    .ap_idle(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_idle),
    .ap_ready(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_ready),
    .rand_in_TDATA(rand_in_TDATA_int_regslice),
    .rand_in_TVALID(rand_in_TVALID_int_regslice),
    .rand_in_TREADY(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_rand_in_TREADY),
    .freq4_V_address0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_address0),
    .freq4_V_ce0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_ce0),
    .freq4_V_we0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_we0),
    .freq4_V_d0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_d0),
    .freq4_V_q0(freq4_V_q0),
    .freq5_V_address0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_address0),
    .freq5_V_ce0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_ce0),
    .freq5_V_we0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_we0),
    .freq5_V_d0(grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_d0),
    .freq5_V_q0(freq5_V_q0)
);

countone_countone_Pipeline_VITIS_LOOP_92_3 grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start),
    .ap_done(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_done),
    .ap_idle(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_idle),
    .ap_ready(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_ready),
    .freq5_V_address0(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq5_V_address0),
    .freq5_V_ce0(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq5_V_ce0),
    .freq5_V_q0(freq5_V_q0),
    .freq4_V_address0(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq4_V_address0),
    .freq4_V_ce0(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq4_V_ce0),
    .freq4_V_q0(freq4_V_q0),
    .chsq_V_2_out(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_chsq_V_2_out),
    .chsq_V_2_out_ap_vld(grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_chsq_V_2_out_ap_vld)
);

countone_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(ap_return)
);

countone_regslice_both #(
    .DataWidth( 8 ))
regslice_both_rand_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(rand_in_TDATA),
    .vld_in(rand_in_TVALID),
    .ack_in(regslice_both_rand_in_U_ack_in),
    .data_out(rand_in_TDATA_int_regslice),
    .vld_out(rand_in_TVALID_int_regslice),
    .ack_out(rand_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_rand_in_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_ready == 1'b1)) begin
            grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_ready == 1'b1)) begin
            grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state5) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_ready == 1'b1)) begin
            grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq4_V_address0 = grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq4_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq4_V_address0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq4_V_address0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_address0;
    end else begin
        freq4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq4_V_ce0 = grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq4_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq4_V_ce0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq4_V_ce0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_ce0;
    end else begin
        freq4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        freq4_V_d0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq4_V_d0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_d0;
    end else begin
        freq4_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        freq4_V_we0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq4_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq4_V_we0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq4_V_we0;
    end else begin
        freq4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq5_V_address0 = grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq5_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq5_V_address0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq5_V_address0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_address0;
    end else begin
        freq5_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq5_V_ce0 = grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_freq5_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq5_V_ce0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq5_V_ce0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_ce0;
    end else begin
        freq5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        freq5_V_d0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq5_V_d0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_d0;
    end else begin
        freq5_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        freq5_V_we0 = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_freq5_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        freq5_V_we0 = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_freq5_V_we0;
    end else begin
        freq5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rand_in_TREADY_int_regslice = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_rand_in_TREADY;
    end else begin
        rand_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_NS_fsm_state5 = ap_NS_fsm[32'd4];

assign ap_return = ((tmp_fu_96_p3[0:0] == 1'b1) ? 32'd4294967295 : ret_fu_104_p4);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start = grp_countone_Pipeline_VITIS_LOOP_59_1_fu_64_ap_start_reg;

assign grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start = grp_countone_Pipeline_VITIS_LOOP_65_2_fu_72_ap_start_reg;

assign grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start = grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_ap_start_reg;

assign rand_in_TREADY = regslice_both_rand_in_U_ack_in;

assign ret_fu_104_p4 = {{grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_chsq_V_2_out[37:6]}};

assign tmp_fu_96_p3 = grp_countone_Pipeline_VITIS_LOOP_92_3_fu_82_chsq_V_2_out[32'd37];


// synthesis translate_off
`include "countone_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //countone

