// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module countone_countone_Pipeline_VITIS_LOOP_92_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        freq5_V_address0,
        freq5_V_ce0,
        freq5_V_q0,
        freq4_V_address0,
        freq4_V_ce0,
        freq4_V_q0,
        chsq_V_2_out,
        chsq_V_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] freq5_V_address0;
output   freq5_V_ce0;
input  [12:0] freq5_V_q0;
output  [9:0] freq4_V_address0;
output   freq4_V_ce0;
input  [12:0] freq4_V_q0;
output  [37:0] chsq_V_2_out;
output   chsq_V_2_out_ap_vld;

reg ap_idle;
reg freq5_V_ce0;
reg freq4_V_ce0;
reg chsq_V_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1057_fu_227_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [9:0] evalue_V_address0;
reg    evalue_V_ce0;
wire   [14:0] evalue_V_q0;
wire   [9:0] evalue_rev_V_address0;
reg    evalue_rev_V_ce0;
wire   [17:0] evalue_rev_V_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln1057_reg_819;
reg   [0:0] icmp_ln1057_reg_819_pp0_iter2_reg;
reg   [0:0] icmp_ln1057_reg_819_pp0_iter3_reg;
reg   [0:0] icmp_ln1057_reg_819_pp0_iter4_reg;
reg   [0:0] icmp_ln1057_reg_819_pp0_iter5_reg;
reg   [0:0] icmp_ln1057_reg_819_pp0_iter6_reg;
reg   [0:0] icmp_ln1057_reg_819_pp0_iter7_reg;
reg   [0:0] icmp_ln1057_reg_819_pp0_iter8_reg;
wire   [0:0] icmp_ln1057_1_fu_330_p2;
reg   [0:0] icmp_ln1057_1_reg_833;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter2_reg;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter3_reg;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter4_reg;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter5_reg;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter6_reg;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter7_reg;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter8_reg;
reg   [0:0] icmp_ln1057_1_reg_833_pp0_iter9_reg;
reg   [17:0] ev_r_V_reg_849;
reg   [17:0] ev_r_V_reg_849_pp0_iter3_reg;
reg   [17:0] ev_r_V_reg_849_pp0_iter4_reg;
reg   [17:0] ev_r_V_reg_849_pp0_iter5_reg;
reg   [17:0] ev_r_V_reg_849_pp0_iter6_reg;
wire   [15:0] ev_V_2_fu_615_p3;
reg   [15:0] ev_V_2_reg_854;
wire   [31:0] zext_ln1169_fu_623_p1;
wire   [31:0] grp_fu_749_p2;
reg   [31:0] r_V_3_reg_865;
wire   [45:0] trunc_ln1168_fu_638_p1;
reg   [45:0] trunc_ln1168_reg_880;
reg   [4:0] tmp_reg_885;
wire   [45:0] chsq_inc_V_fu_657_p3;
reg   [45:0] chsq_inc_V_reg_890;
wire   [63:0] zext_ln573_fu_324_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln573_1_fu_336_p1;
wire   [63:0] zext_ln573_2_fu_347_p1;
reg   [2:0] letters_V_fu_84;
wire   [2:0] letters_V_9_fu_522_p3;
wire    ap_loop_init;
reg   [2:0] letters_V_1_fu_88;
wire   [2:0] letters_V_8_fu_508_p3;
reg   [2:0] letters_V_2_fu_92;
wire   [2:0] letters_V_7_fu_486_p3;
reg   [2:0] letters_V_3_fu_96;
wire   [2:0] letters_V_6_fu_464_p3;
reg   [2:0] letters_V_4_fu_100;
wire   [2:0] letters_V_5_fu_436_p3;
reg   [11:0] index4_V_fu_104;
wire   [11:0] index4_V_2_fu_358_p3;
reg   [11:0] index5_V_fu_108;
wire   [11:0] index5_V_2_fu_366_p3;
reg   [37:0] lhs_V_fu_112;
wire   [37:0] chsq_V_1_fu_732_p3;
reg   [11:0] i_V_fu_116;
wire   [11:0] i_V_2_fu_233_p2;
wire    ap_block_pp0_stage0_01001;
wire   [1:0] trunc_ln_fu_260_p4;
wire   [1:0] tmp_1_fu_290_p4;
wire   [1:0] trunc_ln223_3_fu_270_p4;
wire   [1:0] tmp_2_fu_300_p4;
wire   [1:0] ret_7_fu_280_p4;
wire   [9:0] pattern_V_fu_310_p6;
wire   [11:0] index4_V_1_fu_352_p2;
wire   [11:0] index5_V_1_fu_341_p2;
wire   [0:0] icmp_ln1049_fu_374_p2;
wire   [0:0] icmp_ln1049_1_fu_380_p2;
wire   [0:0] icmp_ln1049_2_fu_386_p2;
wire   [0:0] icmp_ln1049_3_fu_392_p2;
wire   [0:0] and_ln123_1_fu_404_p2;
wire   [0:0] and_ln123_fu_398_p2;
wire   [0:0] icmp_ln1049_4_fu_416_p2;
wire   [2:0] add_ln223_fu_422_p2;
wire   [0:0] and_ln123_2_fu_410_p2;
wire   [2:0] select_ln124_fu_428_p3;
wire   [2:0] add_ln223_1_fu_450_p2;
wire   [0:0] and_ln125_fu_444_p2;
wire   [2:0] select_ln126_fu_456_p3;
wire   [2:0] add_ln223_2_fu_472_p2;
wire   [2:0] select_ln128_fu_478_p3;
wire   [2:0] add_ln223_3_fu_494_p2;
wire   [2:0] select_ln129_fu_500_p3;
wire   [2:0] add_ln223_4_fu_516_p2;
wire   [11:0] trunc_ln1057_fu_574_p1;
wire   [11:0] trunc_ln1057_1_fu_578_p1;
wire   [11:0] select_ln1057_fu_582_p3;
wire   [15:0] zext_ln51_fu_570_p1;
wire   [15:0] ov_V_fu_589_p3;
wire   [0:0] icmp_ln1547_fu_597_p2;
wire   [15:0] sub_ln712_fu_603_p2;
wire   [15:0] sub_ln712_1_fu_609_p2;
wire   [31:0] grp_fu_632_p0;
wire   [17:0] grp_fu_632_p1;
wire   [49:0] grp_fu_632_p2;
wire   [0:0] icmp_ln1549_fu_652_p2;
wire   [0:0] tmp_3_fu_667_p3;
wire   [45:0] lhs_V_1_fu_681_p3;
wire   [0:0] xor_ln1548_fu_675_p2;
wire   [45:0] ret_V_fu_689_p2;
wire   [45:0] ret_V_1_fu_694_p2;
wire   [0:0] and_ln1057_fu_699_p2;
wire   [37:0] tmp_5_fu_704_p4;
wire   [37:0] tmp_6_fu_714_p4;
wire   [37:0] chsq_V_fu_724_p3;
wire   [15:0] grp_fu_749_p0;
wire   [15:0] grp_fu_749_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [49:0] grp_fu_632_p00;
wire   [49:0] grp_fu_632_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_done_reg = 1'b0;
end

countone_countone_Pipeline_VITIS_LOOP_92_3_evalue_V #(
    .DataWidth( 15 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
evalue_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(evalue_V_address0),
    .ce0(evalue_V_ce0),
    .q0(evalue_V_q0)
);

countone_countone_Pipeline_VITIS_LOOP_92_3_evalue_rev_V #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
evalue_rev_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(evalue_rev_V_address0),
    .ce0(evalue_rev_V_ce0),
    .q0(evalue_rev_V_q0)
);

countone_mul_32ns_18ns_50_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 50 ))
mul_32ns_18ns_50_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_632_p0),
    .din1(grp_fu_632_p1),
    .ce(1'b1),
    .dout(grp_fu_632_p2)
);

countone_mul_mul_16ns_16ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16ns_16ns_32_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_749_p0),
    .din1(grp_fu_749_p1),
    .ce(1'b1),
    .dout(grp_fu_749_p2)
);

countone_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_V_fu_116 <= 12'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_V_fu_116 <= i_V_2_fu_233_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            index4_V_fu_104 <= 12'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            index4_V_fu_104 <= index4_V_2_fu_358_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            index5_V_fu_108 <= 12'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            index5_V_fu_108 <= index5_V_2_fu_366_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            letters_V_1_fu_88 <= 3'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            letters_V_1_fu_88 <= letters_V_8_fu_508_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            letters_V_2_fu_92 <= 3'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            letters_V_2_fu_92 <= letters_V_7_fu_486_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            letters_V_3_fu_96 <= 3'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            letters_V_3_fu_96 <= letters_V_6_fu_464_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            letters_V_4_fu_100 <= 3'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            letters_V_4_fu_100 <= letters_V_5_fu_436_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            letters_V_fu_84 <= 3'd0;
        end else if (((icmp_ln1057_fu_227_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            letters_V_fu_84 <= letters_V_9_fu_522_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_V_fu_112 <= 38'd0;
        end else if ((ap_enable_reg_pp0_iter10 == 1'b1)) begin
            lhs_V_fu_112 <= chsq_V_1_fu_732_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln1057_reg_819 <= icmp_ln1057_fu_227_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        chsq_inc_V_reg_890 <= chsq_inc_V_fu_657_p3;
        ev_V_2_reg_854 <= ev_V_2_fu_615_p3;
        ev_r_V_reg_849 <= evalue_rev_V_q0;
        ev_r_V_reg_849_pp0_iter3_reg <= ev_r_V_reg_849;
        ev_r_V_reg_849_pp0_iter4_reg <= ev_r_V_reg_849_pp0_iter3_reg;
        ev_r_V_reg_849_pp0_iter5_reg <= ev_r_V_reg_849_pp0_iter4_reg;
        ev_r_V_reg_849_pp0_iter6_reg <= ev_r_V_reg_849_pp0_iter5_reg;
        icmp_ln1057_1_reg_833_pp0_iter2_reg <= icmp_ln1057_1_reg_833;
        icmp_ln1057_1_reg_833_pp0_iter3_reg <= icmp_ln1057_1_reg_833_pp0_iter2_reg;
        icmp_ln1057_1_reg_833_pp0_iter4_reg <= icmp_ln1057_1_reg_833_pp0_iter3_reg;
        icmp_ln1057_1_reg_833_pp0_iter5_reg <= icmp_ln1057_1_reg_833_pp0_iter4_reg;
        icmp_ln1057_1_reg_833_pp0_iter6_reg <= icmp_ln1057_1_reg_833_pp0_iter5_reg;
        icmp_ln1057_1_reg_833_pp0_iter7_reg <= icmp_ln1057_1_reg_833_pp0_iter6_reg;
        icmp_ln1057_1_reg_833_pp0_iter8_reg <= icmp_ln1057_1_reg_833_pp0_iter7_reg;
        icmp_ln1057_1_reg_833_pp0_iter9_reg <= icmp_ln1057_1_reg_833_pp0_iter8_reg;
        icmp_ln1057_reg_819_pp0_iter2_reg <= icmp_ln1057_reg_819;
        icmp_ln1057_reg_819_pp0_iter3_reg <= icmp_ln1057_reg_819_pp0_iter2_reg;
        icmp_ln1057_reg_819_pp0_iter4_reg <= icmp_ln1057_reg_819_pp0_iter3_reg;
        icmp_ln1057_reg_819_pp0_iter5_reg <= icmp_ln1057_reg_819_pp0_iter4_reg;
        icmp_ln1057_reg_819_pp0_iter6_reg <= icmp_ln1057_reg_819_pp0_iter5_reg;
        icmp_ln1057_reg_819_pp0_iter7_reg <= icmp_ln1057_reg_819_pp0_iter6_reg;
        icmp_ln1057_reg_819_pp0_iter8_reg <= icmp_ln1057_reg_819_pp0_iter7_reg;
        r_V_3_reg_865 <= grp_fu_749_p2;
        tmp_reg_885 <= {{grp_fu_632_p2[49:45]}};
        trunc_ln1168_reg_880 <= trunc_ln1168_fu_638_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1057_fu_227_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1057_1_reg_833 <= icmp_ln1057_1_fu_330_p2;
    end
end

always @ (*) begin
    if (((icmp_ln1057_fu_227_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter9_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1057_reg_819_pp0_iter8_reg == 1'd1))) begin
        chsq_V_2_out_ap_vld = 1'b1;
    end else begin
        chsq_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        evalue_V_ce0 = 1'b1;
    end else begin
        evalue_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        evalue_rev_V_ce0 = 1'b1;
    end else begin
        evalue_rev_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        freq4_V_ce0 = 1'b1;
    end else begin
        freq4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        freq5_V_ce0 = 1'b1;
    end else begin
        freq5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln223_1_fu_450_p2 = (letters_V_3_fu_96 + 3'd1);

assign add_ln223_2_fu_472_p2 = (letters_V_2_fu_92 + 3'd1);

assign add_ln223_3_fu_494_p2 = (letters_V_1_fu_88 + 3'd1);

assign add_ln223_4_fu_516_p2 = (letters_V_fu_84 + 3'd1);

assign add_ln223_fu_422_p2 = (letters_V_4_fu_100 + 3'd1);

assign and_ln1057_fu_699_p2 = (xor_ln1548_fu_675_p2 & icmp_ln1057_1_reg_833_pp0_iter9_reg);

assign and_ln123_1_fu_404_p2 = (icmp_ln1049_3_fu_392_p2 & icmp_ln1049_2_fu_386_p2);

assign and_ln123_2_fu_410_p2 = (and_ln123_fu_398_p2 & and_ln123_1_fu_404_p2);

assign and_ln123_fu_398_p2 = (icmp_ln1049_fu_374_p2 & icmp_ln1049_1_fu_380_p2);

assign and_ln125_fu_444_p2 = (icmp_ln1049_1_fu_380_p2 & and_ln123_1_fu_404_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign chsq_V_1_fu_732_p3 = ((tmp_3_fu_667_p3[0:0] == 1'b1) ? lhs_V_fu_112 : chsq_V_fu_724_p3);

assign chsq_V_2_out = lhs_V_fu_112;

assign chsq_V_fu_724_p3 = ((and_ln1057_fu_699_p2[0:0] == 1'b1) ? tmp_5_fu_704_p4 : tmp_6_fu_714_p4);

assign chsq_inc_V_fu_657_p3 = ((icmp_ln1549_fu_652_p2[0:0] == 1'b1) ? trunc_ln1168_reg_880 : 46'd35184372088832);

assign ev_V_2_fu_615_p3 = ((icmp_ln1547_fu_597_p2[0:0] == 1'b1) ? sub_ln712_fu_603_p2 : sub_ln712_1_fu_609_p2);

assign evalue_V_address0 = zext_ln573_fu_324_p1;

assign evalue_rev_V_address0 = zext_ln573_fu_324_p1;

assign freq4_V_address0 = zext_ln573_2_fu_347_p1;

assign freq5_V_address0 = zext_ln573_1_fu_336_p1;

assign grp_fu_632_p0 = grp_fu_632_p00;

assign grp_fu_632_p00 = r_V_3_reg_865;

assign grp_fu_632_p1 = grp_fu_632_p10;

assign grp_fu_632_p10 = ev_r_V_reg_849_pp0_iter6_reg;

assign grp_fu_749_p0 = zext_ln1169_fu_623_p1;

assign grp_fu_749_p1 = zext_ln1169_fu_623_p1;

assign i_V_2_fu_233_p2 = (i_V_fu_116 + 12'd1);

assign icmp_ln1049_1_fu_380_p2 = ((letters_V_2_fu_92 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln1049_2_fu_386_p2 = ((letters_V_1_fu_88 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln1049_3_fu_392_p2 = ((letters_V_fu_84 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln1049_4_fu_416_p2 = ((letters_V_4_fu_100 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln1049_fu_374_p2 = ((letters_V_3_fu_96 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln1057_1_fu_330_p2 = ((i_V_fu_116 < 12'd3125) ? 1'b1 : 1'b0);

assign icmp_ln1057_fu_227_p2 = ((i_V_fu_116 == 12'd3750) ? 1'b1 : 1'b0);

assign icmp_ln1547_fu_597_p2 = ((zext_ln51_fu_570_p1 > ov_V_fu_589_p3) ? 1'b1 : 1'b0);

assign icmp_ln1549_fu_652_p2 = ((tmp_reg_885 == 5'd0) ? 1'b1 : 1'b0);

assign index4_V_1_fu_352_p2 = (index4_V_fu_104 + 12'd1);

assign index4_V_2_fu_358_p3 = ((icmp_ln1057_1_fu_330_p2[0:0] == 1'b1) ? index4_V_fu_104 : index4_V_1_fu_352_p2);

assign index5_V_1_fu_341_p2 = (index5_V_fu_108 + 12'd1);

assign index5_V_2_fu_366_p3 = ((icmp_ln1057_1_fu_330_p2[0:0] == 1'b1) ? index5_V_1_fu_341_p2 : index5_V_fu_108);

assign letters_V_5_fu_436_p3 = ((and_ln123_2_fu_410_p2[0:0] == 1'b1) ? select_ln124_fu_428_p3 : letters_V_4_fu_100);

assign letters_V_6_fu_464_p3 = ((and_ln125_fu_444_p2[0:0] == 1'b1) ? select_ln126_fu_456_p3 : letters_V_3_fu_96);

assign letters_V_7_fu_486_p3 = ((and_ln123_1_fu_404_p2[0:0] == 1'b1) ? select_ln128_fu_478_p3 : letters_V_2_fu_92);

assign letters_V_8_fu_508_p3 = ((icmp_ln1049_3_fu_392_p2[0:0] == 1'b1) ? select_ln129_fu_500_p3 : letters_V_1_fu_88);

assign letters_V_9_fu_522_p3 = ((icmp_ln1049_3_fu_392_p2[0:0] == 1'b1) ? 3'd0 : add_ln223_4_fu_516_p2);

assign lhs_V_1_fu_681_p3 = {{lhs_V_fu_112}, {8'd0}};

assign ov_V_fu_589_p3 = {{select_ln1057_fu_582_p3}, {4'd0}};

assign pattern_V_fu_310_p6 = {{{{{trunc_ln_fu_260_p4}, {tmp_1_fu_290_p4}}, {trunc_ln223_3_fu_270_p4}}, {tmp_2_fu_300_p4}}, {ret_7_fu_280_p4}};

assign ret_7_fu_280_p4 = {{letters_V_fu_84[2:1]}};

assign ret_V_1_fu_694_p2 = (lhs_V_1_fu_681_p3 - chsq_inc_V_reg_890);

assign ret_V_fu_689_p2 = (lhs_V_1_fu_681_p3 + chsq_inc_V_reg_890);

assign select_ln1057_fu_582_p3 = ((icmp_ln1057_1_reg_833[0:0] == 1'b1) ? trunc_ln1057_fu_574_p1 : trunc_ln1057_1_fu_578_p1);

assign select_ln124_fu_428_p3 = ((icmp_ln1049_4_fu_416_p2[0:0] == 1'b1) ? 3'd6 : add_ln223_fu_422_p2);

assign select_ln126_fu_456_p3 = ((icmp_ln1049_fu_374_p2[0:0] == 1'b1) ? 3'd0 : add_ln223_1_fu_450_p2);

assign select_ln128_fu_478_p3 = ((icmp_ln1049_1_fu_380_p2[0:0] == 1'b1) ? 3'd0 : add_ln223_2_fu_472_p2);

assign select_ln129_fu_500_p3 = ((icmp_ln1049_2_fu_386_p2[0:0] == 1'b1) ? 3'd0 : add_ln223_3_fu_494_p2);

assign sub_ln712_1_fu_609_p2 = (ov_V_fu_589_p3 - zext_ln51_fu_570_p1);

assign sub_ln712_fu_603_p2 = (zext_ln51_fu_570_p1 - ov_V_fu_589_p3);

assign tmp_1_fu_290_p4 = {{letters_V_3_fu_96[2:1]}};

assign tmp_2_fu_300_p4 = {{letters_V_1_fu_88[2:1]}};

assign tmp_3_fu_667_p3 = lhs_V_fu_112[32'd37];

assign tmp_5_fu_704_p4 = {{ret_V_fu_689_p2[45:8]}};

assign tmp_6_fu_714_p4 = {{ret_V_1_fu_694_p2[45:8]}};

assign trunc_ln1057_1_fu_578_p1 = freq4_V_q0[11:0];

assign trunc_ln1057_fu_574_p1 = freq5_V_q0[11:0];

assign trunc_ln1168_fu_638_p1 = grp_fu_632_p2[45:0];

assign trunc_ln223_3_fu_270_p4 = {{letters_V_2_fu_92[2:1]}};

assign trunc_ln_fu_260_p4 = {{letters_V_4_fu_100[2:1]}};

assign xor_ln1548_fu_675_p2 = (tmp_3_fu_667_p3 ^ 1'd1);

assign zext_ln1169_fu_623_p1 = ev_V_2_reg_854;

assign zext_ln51_fu_570_p1 = evalue_V_q0;

assign zext_ln573_1_fu_336_p1 = index5_V_fu_108;

assign zext_ln573_2_fu_347_p1 = index4_V_fu_104;

assign zext_ln573_fu_324_p1 = pattern_V_fu_310_p6;

endmodule //countone_countone_Pipeline_VITIS_LOOP_92_3
